---
title: "Practical suggestions for improving your scatterplots"
author: "Steve Simon"
output: powerpoint_presentation
---

### Abstract

The scatterplot is a simple display of the relationship between two or sometime three variables. You have a wide range of options for displaying a scatterplot. In particular, you can control the location, size, shape, and color of the points in your scatterplot. Careful selection among these options will allow your audience to rapidly and accurately understand this relationship. Here are some important dos and don'ts. Don't use a gradient to represent a nominal variable. Use open circles rather than closed circles if there is a lot of overprinting. Vary the size or the shape of your data points, but not both. Always pair color with another feature in your plots. Most importantly, never blindly accept the first graph that comes out of your software program. Revise your graphs as often as you revise your writing.

### General principles

+ "I'm the only genius who understands my filing system."
  + This does not apply to graphs
+ Two quantifiable criteria for an effective graph
  + Speed
  + Accuracy
